*! version 0.1.1  12Sep2014
*! Copyright (C) World Bank 2017-2024 
//error function
cap program drop primus_message
program define primus_message
	syntax, error(numlist max=1)
	//subscription error
	if `error'==400 noi dis "{err}400 Unknown Error"
	if `error'==401 noi dis "{err}401 Unauthorized Error, Token is Invalid/Expired"
	
	//Plugin errors
	if `error'==403 noi dis "{err}403 Not an authorized user to download (when the plugin user is not the same as input UPI in method 0 and plugin user is not a super admin)"
	if `error'==405 noi dis "{err}405 Invalid syntax parameters such as missing processid()"
	if `error'==500 noi dis "{err}500 Unknown error"
	if `error'==601 noi dis "{err}601 Internet bad URL format"
	if `error'==602 noi dis "{err}602 Internet authentication canceled"
	if `error'==603 noi dis "{err}603 Internet connectivity failure"
	if `error'==604 noi dis "{err}604 Internet primus server unreachable"
	if `error'==605 noi dis "{err}605 Internet unknown local error"
	if `error'==610 noi dis "{err}610 Response error invalid content type header"
	if `error'==611 noi dis "{err}611 Response error invalid file name header"
	if `error'==612 noi dis "{err}612 Response error invalid content length header"
	if `error'==613 noi dis "{err}613 Response error invalid file extension"
	if `error'==614 noi dis "{err}614 Response error invalid status header"
	if `error'==701 noi dis "{err}701 Plugin usage error. The provided input parameters do not meet the required criteria."
	if `error'==702 noi dis "{err}702 File I/O error, local file system access"
	*if `error'==702 noi dis "{err}702 The Token does not exist, please execute method 8 for specific server environment 1/2/3/4 (DEV/QA/UAT/PROD)"
	
	//API errors
	if `error'==801 noi dis "{err}801 Authorization validation error: User email cannot be empty"
	if `error'==802 noi dis "{err}802 Operation failed: User lacks Approver/Uploader role for specified country"
	if `error'==803 noi dis "{err}803 The specified folder does not exist in the current process"
	if `error'==804 noi dis "{err}804 The specified folder does not allow files with this extension"
	if `error'==805 noi dis "{err}805 For Harmonized transactions the filename must be of the format, SurveyID_Module"
	if `error'==806 noi dis "{err}806 For Harmonized transactions the specified module in the file name does not exist in this process"
	if `error'==807 noi dis "{err}807 Action denied: Pending transaction exists for same survey, year, and country"
	*if `error'==808 noi dis "{err}808 An error occurred while generating the Transaction ID"
	if `error'==808 noi dis "{err}808 We couldn't find any surveys that match your search criteria. Please refine your search"
	if `error'==809 noi dis "{err}809 Only harmonized processes are allowed, raw processes are not allowed"
	if `error'==810 noi dis "{err}810 The specified SurveyID does not match the specified Transaction ID"
	*if `error'==811 noi dis "{err}811 Only RAW process is allowed, Harmonized process is not allowed"
	if `error'==811 noi dis "{err}811 The same file already exist for the same survey id"
	if `error'==812 noi dis "{err}812 Process ID not found"
	if `error'==813 noi dis "{err}813 The provided transaction ID is incorrect"	
	if `error'==814 noi dis "{err}814 No Process ID is available"	
	if `error'==815 noi dis "{err}815 No folders are available in this process"	
	*if `error'==816 noi dis "{err}816 Invalid Survey ID. The master version exceeds the sequence."	
	if `error'==816 noi dis "{err}816 An error occurred while validating the survey ID: One or more errors occurred."	
	if `error'==821 noi dis "{err}821 Transaction status is not valid"		
	if `error'==822 noi dis "{err}822 Transaction is in DRAFT mode"	
	*if `error'==823 noi dis "{err}Transaction is already rejected by another Regional/Global Approver"	
	if `error'==823 noi dis "{err}823 An error occurred. Please try again later"	
	if `error'==824 noi dis "{err}824 No Conflicts. Finalizer can't take actions yet"	
	if `error'==825 noi dis "{err}825 Transaction already Rejected"		
	if `error'==826 noi dis "{err}826 Please provide a valid TransactionId"	
	if `error'==827 noi dis "{err}827 Transaction already Confirmed"			
	if `error'==828 noi dis "{err}828 Invalid ProcessID"	
	if `error'==829 noi dis "{err}829 ProcessID not assigned to you"	
	if `error'==830 noi dis "{err}830 ProcessID is not valid with the TransactionID"	
	if `error'==831 noi dis "{err}831 Transaction is in COMPLETE mode"	
	if `error'==832 noi dis "{err}832 Transaction is in REJECT mode"	
	if `error'==836 noi dis "{err}836 Operation failed: User lacks Approver role for specified country"	
	if `error'==842 noi dis "{err}842 No records available in this Transaction"	
	if `error'==851 noi dis "{err}851 Operation failed: Transaction is in PENDING status"	
	if `error'==852 noi dis "{err}852 Operation failed: Transaction is in REJECTED status"		
	if `error'==853 noi dis "{err}853 Transaction is in COMPLETE status"	
	if `error'==854 noi dis "{err}854 Operation failed: Process is in Inactive status."			
	if `error'==855 noi dis "{err}855 Operation failed: The transaction should be uploaded with the XML file"	
	if `error'==856 noi dis "{err}856 Transaction is in COMPLETE mode"
	if `error'==857 noi dis "{err}857 Transaction is in REJECT mode"	
	if `error'==858 noi dis "{err}858 Transaction is in PENDING mode, so it can't be confirmed."
	if `error'==859 noi dis "{err}859 File transfer from the TEMP folder to the WRK folder is in progress. Please try again later."
	if `error'==860 noi dis "{err}860 Transaction is in DRAFT mode"	
	if `error'==861 noi dis "{err}861 Operation failed: Uploader can't approve a transaction"	
	if `error'==870 noi dis "{err}870 The same file already exists for the same SurveyID"	
	if `error'==871 noi dis "{err}871 Please provide a valid Decision"	
	if `error'==2222 noi dis "{err}2222 The specified input server parameter is invalid or incorrect."
end
